### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by exacs**

### CODE REVIEW

**Comment by exacs** [comment]
Thanks for your feedback!

- I have replaced `renewCache` with `fetchCourses` as you have suggested :)
- Also I have made an implementation of `stripIndent` that you can see in this commit: https://github.com/KTH/lms-web/pull/4/commits/03214bf1494bc3bffb3bd5efc2641a5d1a06db20. Not sure how understandable it is since it mixes **template tags** and **RegEx** which are something that *we don't see everyday* and imho an ugly combination of concepts (I had to search how to implement something like this).

I want your opinions in this last point because we can also remove entirely the `stripIndent` function. Up to you @me97esn @Delodax !

**Comment by Delodax** [comment]
@exacs : The `stripIndent` looks good imo. The most complicated part for me was understanding the regex :P Good opportunity to read more about _Tagged Templates_.

Standard complained about that `strings[i+1]` should be `strings[i + 1]`, that's all I think.

**Comment by kaj** [comment]
How about putting the lines in separate strings and join them?  Like so:

```javascript
    const statusStr = [
        `APPLICATION_STATUS: ${status ? 'OK' : 'ERROR'}`,
        `CANVAS_KEY: ...`,
    ].join('\n')
```

**Comment by Delodax** [comment]
@kaj : Looks simple 'n' clean!

**Pull request merged**
